server:
  port: 0

spring:
  application:
    name: hot-catalog-service

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 1

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: hot-catalog-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: greenbasket
    password: greenbasket
    listener:
      simple:
        auto-startup: true

  cloud:
    bus:
      enabled: true
    openfeign:
      micrometer:
        enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${local.server.port}
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    hotcatalogservice: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,info,busrefresh
  health:
    rabbit:
      enabled: false


  # Catalog Service Exception Messages
  # catalog-service:
  #   exception: 
